### ISSUE TITLE
Use Commit Hashes to Version Reusable Github Actions Tasks

### ISSUE THREAD

**Issue by sarina** [openedx/.github#165]
In response to https://www.bleepingcomputer.com/news/security/supply-chain-attack-on-popular-github-action-exposes-ci-cd-secrets/ we should move to pinning GitHub Action versions by commit hash.

Some resources:

* Not natively supported: https://github.com/actions/runner/issues/2195
* Dependabot may support this: https://github.com/dependabot/dependabot-core/issues/4691
* We may be able to run [pinact](https://github.com/suzuki-shunsuke/pinact) as a one-off and then leverage Dependabot after that.

**Comment by farhan** [comment]
@arbrandes We tried https://github.com/suzuki-shunsuke/pinact, it's working fine
How can we run it in all the repositories, this what we were discussing yesterday
We are on the edge of getting relax from the XBlock extraction work, we have prioritize it as next.

**Comment by irfanuddinahmad** [comment]
Dependabot alone is not a strict enforcement mechanism for SHA pinning. It is excellent for ongoing updates, but it does not by itself guarantee that repos using tag-based `uses:` refs will automatically move to SHA-pinned refs in the next PR.

Proposed path forward:

1. One-time baseline migration to SHA-pinned action refs
    Convert workflow `uses:` references from tags to full commit SHA with a human-readable version comment.
    Example format:
`        uses: actions/checkout@<40-char-sha> # vX.Y.Z `
2. Keep Dependabot for ongoing maintenance
    Continue weekly github-actions updates in repos.
    After the baseline is SHA-pinned, Dependabot can keep SHA + comment updated over time.
3. Add enforcement so tags cannot be reintroduced
    Add a required CI check (for example `pinact run --check `or equivalent policy check) that fails if external actions are not pinned to full SHA. This provides durable protection against future drift back to tags.
4. Optional platform guardrail
    If available in org settings, enable GitHub Actions policy requiring full-length commit SHA pinning for actions.

**Comment by sarina** [comment]
I was working in a personal repo and just noticed the Actions setting requiring actions to be pinned to a SHA. Maybe this is something we want to consider turning on everywhere.

<img width="842" height="469" alt="Image" src="https://github.com/user-attachments/assets/7bb559e1-82c9-4ef9-a509-8cbd9dde1d6b" />

**Comment by irfanuddinahmad** [comment]
Yes, Thanks!
I think this org-level setting could replace the "required CI check" approach we were considering (e.g. pinact run --check). Since it's enforced at the GitHub platform level rather than as a workflow step, it's actually stronger — workflows with unpinned actions simply won't run, regardless of what's in the YAML.

The tradeoff is that the setting gives less actionable feedback to contributors compared to a pinact CI check, which points to specific files and lines. So the approach could be:

1. Use pinact as a one-off migration to pin everything to SHAs
2. Enable Dependabot to keep SHAs up to date going forward
3. Turn on this org-level setting as the durable enforcement — replacing the need for a dedicated CI check

**Comment by irfanuddinahmad** [comment]
useful building blocks:

[clone_org.py](https://github.com/openedx/repo-tools/blob/8f82179eb8fb65bae2f0e8f433dba3b7f6c7a60a/edx_repo_tools/dev/clone_org.py#L1) — clones an entire GitHub org with filtering (archived, forks, patterns). The "checkout all repos" step.
[pull_request_creator/](https://github.com/openedx/repo-tools/tree/8f82179eb8fb65bae2f0e8f433dba3b7f6c7a60a/edx_repo_tools/pull_request_creator) — bulk PR creation across repos after modifications.


above used by [bulk repo update tool ](https://github.com/openedx/.github/actions/workflows/bulk_repo_update.yml)

**Comment by farhan** [comment]
@feanil

Pasting the list here so we will have an idea which PRs have been merged and which ones are left.

1. [x] https://github.com/openedx/XBlock/pull/913
2. [ ] https://github.com/openedx/edx-notes-api/pull/549
3. [ ] https://github.com/openedx/event-bus-redis/pull/233
4. [ ] https://github.com/openedx/opaque-keys/pull/445
5. [ ] https://github.com/openedx/openedx-core/pull/597
6. [ ] https://github.com/openedx/.github/pull/228
7. [ ] https://github.com/openedx/repo-tools/pull/706
8. [ ] https://github.com/openedx/wg-build-test-release/pull/573
9. [ ] https://github.com/openedx/RecommenderXBlock/pull/133
10. [ ] https://github.com/openedx/acid-block/pull/267
11. [ ] https://github.com/openedx/api-doc-tools/pull/390
12. [ ] https://github.com/openedx/auth-backends/pull/426
13. [ ] https://github.com/openedx/brand-openedx/pull/48
14. [ ] https://github.com/openedx/browserslist-config/pull/24
15. [ ] https://github.com/openedx/cc2olx/pull/304
16. [ ] https://github.com/openedx/ccx-keys/pull/187
17. [ ] https://github.com/openedx/code-annotations/pull/225
18. [ ] https://github.com/openedx/codejail/pull/303
19. [ ] https://github.com/openedx/codejail-includes/pull/24
20. [ ] https://github.com/openedx/codejail-service/pull/87
21. [ ] https://github.com/openedx/completion/pull/431
22. [ ] https://github.com/openedx/course-discovery/pull/4725
23. [ ] https://github.com/openedx/credentials/pull/2988
24. [ ] https://github.com/openedx/credentials-themes/pull/1079
25. [ ] https://github.com/openedx/crowdsourcehinter/pull/272
26. [ ] https://github.com/openedx/cypress-e2e-tests/pull/181
27. [ ] https://github.com/openedx/didkit-python/pull/5
28. [ ] https://github.com/openedx/django-config-models/pull/461
29. [ ] https://github.com/openedx/django-pyfs/pull/297
30. [ ] https://github.com/openedx/django-require/pull/18
31. [ ] https://github.com/openedx/django-user-tasks/pull/458
32. [ ] https://github.com/openedx/django-wiki/pull/326
33. [ ] https://github.com/openedx/edx-ace/pull/378
34. [ ] https://github.com/openedx/edx-bootstrap/pull/343
35. [ ] https://github.com/openedx/edx-bulk-grades/pull/177
36. [ ] https://github.com/openedx/edx-celeryutils/pull/397
37. [ ] https://github.com/openedx/edx-cookiecutters/pull/568
38. [ ] https://github.com/openedx/edx-django-sites-extensions/pull/157
39. [ ] https://github.com/openedx/edx-django-utils/pull/536
40. [ ] https://github.com/openedx/edx-drf-extensions/pull/560
41. [ ] https://github.com/openedx/edx-enterprise/pull/2621
42. [ ] https://github.com/openedx/edx-enterprise-data/pull/673
43. [ ] https://github.com/openedx/edx-lint/pull/543
44. [ ] https://github.com/openedx/edx-milestones/pull/108
45. [ ] https://github.com/openedx/edx-ora2/pull/2403
46. [ ] https://github.com/openedx/edx-organizations/pull/539
47. [ ] https://github.com/openedx/edx-proctoring/pull/1326
48. [ ] https://github.com/openedx/edx-rbac/pull/442
49. [ ] https://github.com/openedx/edx-repo-health/pull/663
50. [ ] https://github.com/openedx/edx-rest-api-client/pull/442
51. [ ] https://github.com/openedx/edx-search/pull/271
52. [ ] https://github.com/openedx/edx-submissions/pull/350
53. [ ] https://github.com/openedx/edx-toggles/pull/465
54. [ ] https://github.com/openedx/edx-ui-toolkit/pull/516
55. [ ] https://github.com/openedx/edx-val/pull/610
56. [ ] https://github.com/openedx/edx-when/pull/359
57. [ ] https://github.com/openedx/enmerkar-underscore/pull/246
58. [ ] https://github.com/openedx/enterprise-access/pull/1008
59. [ ] https://github.com/openedx/enterprise-catalog/pull/1134
60. [ ] https://github.com/openedx/eslint-config/pull/186
61. [ ] https://github.com/openedx/event-bus-kafka/pull/345
62. [ ] https://github.com/openedx/event-tracking/pull/407
63. [ ] https://github.com/openedx/forum/pull/278
64. [ ] https://github.com/openedx/frontend-app-admin-portal/pull/1789
65. [ ] https://github.com/openedx/frontend-app-catalog/pull/126
66. [ ] https://github.com/openedx/frontend-app-enterprise-public-catalog/pull/515
67. [ ] https://github.com/openedx/frontend-app-gradebook/pull/579
68. [ ] https://github.com/openedx/frontend-app-instructor-dashboard/pull/209
69. [ ] https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/1501
70. [ ] https://github.com/openedx/frontend-app-learner-record/pull/682
71. [ ] https://github.com/openedx/frontend-app-ora-grading/pull/490
72. [ ] https://github.com/openedx/frontend-base-compat/pull/4
73. [ ] https://github.com/openedx/frontend-build/pull/689
74. [ ] https://github.com/openedx/frontend-component-cookie-policy-banner/pull/452
75. [ ] https://github.com/openedx/frontend-components-tinymce-advanced-plugins/pull/39
76. [ ] https://github.com/openedx/frontend-dev-utils/pull/10
77. [ ] https://github.com/openedx/frontend-enterprise/pull/498
78. [ ] https://github.com/openedx/frontend-lib-special-exams/pull/174
79. [ ] https://github.com/openedx/frontend-platform/pull/883
80. [ ] https://github.com/openedx/frontend-plugin-framework/pull/122
81. [ ] https://github.com/openedx/frontend-plugin-notifications/pull/116
82. [ ] https://github.com/openedx/frontend-template-application/pull/1002
83. [ ] https://github.com/openedx/frontend-template-site/pull/19
84. [ ] https://github.com/openedx/help-tokens/pull/325
85. [ ] https://github.com/openedx/i18n-tools/pull/261
86. [ ] https://github.com/openedx/license-manager/pull/883
87. [ ] https://github.com/openedx/mockprock/pull/64
88. [ ] https://github.com/openedx/olxcleaner/pull/30
89. [ ] https://github.com/openedx/openedx-ai-extensions/pull/225
90. [ ] https://github.com/openedx/openedx-app-android/pull/480
91. [ ] https://github.com/openedx/openedx-app-firebase-analytics-android/pull/7
92. [ ] https://github.com/openedx/openedx-app-firebase-analytics-ios/pull/6
93. [ ] https://github.com/openedx/openedx-app-foundation-android/pull/21
94. [ ] https://github.com/openedx/openedx-app-foundation-ios/pull/29
95. [ ] https://github.com/openedx/openedx-app-ios/pull/660
96. [ ] https://github.com/openedx/openedx-atlas/pull/73
97. [ ] https://github.com/openedx/openedx-authz/pull/292
98. [ ] https://github.com/openedx/openedx-calc/pull/202
99. [ ] https://github.com/openedx/openedx-chem/pull/160
100. [ ] https://github.com/openedx/openedx-events/pull/576
101. [ ] https://github.com/openedx/openedx-filters/pull/360
102. [ ] https://github.com/openedx/openedx-k8s-harmony/pull/189
103. [ ] https://github.com/openedx/openedx-translations/pull/73448
104. [ ] https://github.com/openedx/openedx-user-groups/pull/23
105. [ ] https://github.com/openedx/openedx-webhooks/pull/423
106. [ ] https://github.com/openedx/openedx-wordpress-ecommerce/pull/127
107. [ ] https://github.com/openedx/paragon/pull/4301
108. [ ] https://github.com/openedx/pr_watcher_notifier/pull/11
109. [ ] https://github.com/openedx/pytest-repo-health/pull/375
110. [ ] https://github.com/openedx/sample-plugin/pull/53
111. [ ] https://github.com/openedx/staff-graded-xblock/pull/379
112. [ ] https://github.com/openedx/stylelint-config-edx/pull/56
113. [ ] https://github.com/openedx/super-csv/pull/261
114. [ ] https://github.com/openedx/taxonomy-connector/pull/305
115. [ ] https://github.com/openedx/tinymce-language-selector/pull/30
116. [ ] https://github.com/openedx/training-courses/pull/78
117. [ ] https://github.com/openedx/tutor-contrib-aspects-sample/pull/2
118. [ ] https://github.com/openedx/tutor-contrib-platform-notifications/pull/64
119. [ ] https://github.com/openedx/typescript-config/pull/19
120. [ ] https://github.com/openedx/xblock-lti-consumer/pull/655
121. [ ] https://github.com/openedx/xblock-skill-tagging/pull/56

**Comment by feanil** [comment]
@farhan @irfanuddinahmad I've merged everything that doesn't need an update here. Please take a look at the rest of the open PRs and let me know when they're ready for another pass/merging.

**Comment by irfanuddinahmad** [comment]
> [@farhan](https://github.com/farhan) [@irfanuddinahmad](https://github.com/irfanuddinahmad) I've merged everything that doesn't need an update here. Please take a look at the rest of the open PRs and let me know when they're ready for another pass/merging.

@feanil @farhan --- Following PRs have been updated with fixes

https://github.com/openedx/edx-django-utils/pull/536
https://github.com/openedx/enmerkar-underscore/pull/246
https://github.com/openedx/edx-val/pull/610
https://github.com/openedx/tutor-contrib-aspects-sample/pull/2
https://github.com/openedx/enterprise-catalog/pull/1134
https://github.com/openedx/frontend-enterprise/pull/499

Following has a pre-existing failure on main:

https://github.com/openedx/edx-cookiecutters/pull/568 — tests (py) job failing but it's a pre-existing failure on main, not caused by this PR. run_ida_tests passes.

Fix on main: https://github.com/openedx/edx-cookiecutters/pull/569

**Comment by pomegranited** [comment]
Hi @irfanuddinahmad Thank you for working on this issue!

Can you help me understand how this changes our review process for the automated dependabot updates? I can see that we're getting SHA commit hashes now instead of version tags, e.g. https://github.com/openedx/completion/pull/438. But do I (as a core committer) need to validate this update differently than I was before?

**Comment by irfanuddinahmad** [comment]
Hi @pomegranited! Great question — the short answer is: **the review process is largely the same**, but here's what's different to be aware of.

**What changed in the workflow YAML**

References that used to look like:
```yaml
uses: actions/checkout@v4.2.2
```
now look like:
```yaml
uses: actions/checkout@abc1234...def  # v4.2.2
```

The human-readable version tag is preserved as a comment, so you can still see at a glance what version is being used.

**What Dependabot PRs look like now**

Dependabot understands SHA-pinned refs and will continue to open PRs when a new version is available. The PR title/description will still tell you the version change (e.g. "bump codecov/codecov-action from 6.0.1 to 7.0.0"), and the diff will show the old SHA being replaced by the new SHA + updated version comment. You can see an example at https://github.com/openedx/completion/pull/438.

**As a core committer, your review doesn't change much:**
- Still rely on Dependabot's PR title and release notes for the version change info
- The `# vX.Y.Z` comment in the diff confirms the version at a glance
- If anything looks off (e.g. the comment version doesn't match the PR title), that's worth investigating

The main benefit to you is actually **more confidence** — because the SHA is cryptographically bound to the exact code that will run, a tag re-pointing attack (where a maintainer silently moves a tag to different code) is no longer possible.
